### ISSUE TITLE
Add Flaticons

### ISSUE THREAD

**Issue by JideGuru** [Onyebueke-Emmanuel/useful-design-tools-for-developers#1]
Hi.
i want to make a suggestion of adding [FlatIcons](https://www.flaticon.com/) under the icons category.

Thanks

**Comment by dev-olly** [comment]
I make you a contributor so you add as much as you know

**Comment by JideGuru** [comment]
> I make you a contributor so you add as much as you know

Ok thanks. i will be waiting
